export const MOCK_DATA = [
  {
    BANK: 'ABHYUDAYA COOPERATIVE BANK LIMITED',
    IFSC: 'ABHY0065001',
    BRANCH: 'RTGS-HO',
    ADDRESS: 'ABHYUDAYA BANK BLDG., B.NO.71, NEHRU NAGAR, KURLA (E), MUMBAI-400024',
    CITY1: 'MUMBAI',
    CITY2: 'GREATER MUMBAI',
    STATE: 'MAHARASHTRA',
    'STD CODE': 22.0,
    PHONE: '25260173',
  },
  {
    BANK: 'ABHYUDAYA COOPERATIVE BANK LIMITED',
    IFSC: 'ABHY0065002',
    BRANCH: 'ABHYUDAYA NAGAR',
    ADDRESS: 'ABHYUDAYA EDUCATION SOCIETY, OPP. BLDG. NO. 18, ABHYUDAYA NAGAR, KALACHOWKY, MUMBAI - 400033',
    CITY1: 'MUMBAI',
    CITY2: 'GREATER MUMBAI',
    STATE: 'MAHARASHTRA',
    'STD CODE': 22.0,
    PHONE: '24702643',
  },
  {
    BANK: 'THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK',
    IFSC: 'ADCC0000048',
    BRANCH: 'BELKHED BRANCH',
    ADDRESS: 'THE AKOLA DISTRICT CENTRAL COOP. BANK LTD.,BRANCH BELKHED, AT. PO. BELKHED, TQ. TELHARA, DIST.AKOLA. 444108',
    CITY1: 'TELHARA',
    CITY2: 'AKOLA',
    STATE: 'MAHARASHTRA',
    'STD CODE': 724.0,
    PHONE: '2415105',
  },
  {
    BANK: 'THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK',
    IFSC: 'ADCC0000049',
    BRANCH: 'AADSUL \u252c\u00e1BRANCH',
    ADDRESS: 'THE AKOLA DISTRICT CENTRAL COOP. BANK LTD., BRANCH ADSUL, AT. PO. ADSUL, TQ. TELHARA, DIST. AKOLA. 444108',
    CITY1: 'TELHARA',
    CITY2: 'AKOLA',
    STATE: 'MAHARASHTRA',
    'STD CODE': 724.0,
    PHONE: '2415105',
  }];

export const BANK_NAMES = ['ABHYUDAYA COOPERATIVE BANK LIMITED', 'THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK'];

export const BRANCH_NAMES_ABHYUDAYA = ['RTGS-HO', 'ABHYUDAYA NAGAR'];

export const BRANCH_NAMES_AKOLA = ['AADSUL BRANCH', 'BELKHED BRANCH'];

export const BANK_DETAILS = {
  BANK: 'ABHYUDAYA COOPERATIVE BANK LIMITED',
  IFSC: 'ABHY0065001',
  BRANCH: 'RTGS-HO',
};
